### ISSUE TITLE
`payto://eth` doesn't follow specification

### ISSUE THREAD

**Issue by Pandapip1** [core-laboratories/payto#10]
### OS and version

Windows 11

### Bug

When generating an Ethereum payment URI, the output is not always valid according to https://git.gnunet.org/gana.git/tree/payto-payment-target-types/eth.txt

### Input

**Mode**: `ICAN`
**Transport Network**: `ETH`
**Address**: `0x1234`
**Amount**: `3.14`
**Currency code / Token code / Token address**: `0x5678`

### Output

**URI**: `payto://eth/0x1234?amount=0X5678:3.14`

### Input

- Asks for Chain ID (optional)

### Output

- Outputs in the following format: `"payto://eth/" addr [ "@" chain_id ] [ "?" opts ]`
- Token address is not fully capitalized

### Commit hash

388846cb8decd0b5de940930064282a4e76f979f

**Comment by rastislavcore** [comment]
Thank you, we will implement the optional fields and updates as follows:

- Chain ID as an optional field
- Token address will be with mixed case to keep the checksum
- we are keeping colon `:` to indicate asset on the network in the amount field

Please, elaborate on the opts as optional parameters. @Pandapip1 

Thank you for your contribution.

**Comment by Pandapip1** [comment]
`opts` are as defined in the RFC.

**Comment by rastislavcore** [comment]
Almost ready to be tested and deployed.

**Comment by Pandapip1** [comment]
> Almost ready to be tested and deployed.

Wow! That was fast!

**Comment by rastislavcore** [comment]
Fixed with #11
