### ISSUE TITLE
Ethereum payment type accepts non-contract currencies

### ISSUE THREAD

**Issue by Pandapip1** [core-laboratories/payto#12]
### OS and version

windows

### Bug

This application, when using the ethereum payment type, accepts 3-letter currencies, which are disallowed by the spec (it must be either blank to indicate the native currency, or it must be an `0x`-prefixed checksummed address.

### Reproduce Bug

Choose the ethereum payment type. Type in a something other than a contract address or the empty string.

### Expected behavior

An error or warning should be displayed.

**Comment by rastislavcore** [comment]
We are expanding on [RFC 8905](https://datatracker.ietf.org/doc/html/rfc8905) and are not limited to Ethereum. Because of other currencies, we will not accept them for now, but later we can re-open. Please, provide more rationale, if you think it is required.

Thank you for your contribution.

**Comment by Pandapip1** [comment]
I meant specifically when the Ethereum type is selected. Obviously for other types, those currencies should be allowed.

**Comment by rastislavcore** [comment]
Moved to enhancement

**Comment by Pandapip1** [comment]
@rastislavcore FYI - your feature suggestion config doesn't actually add an enhancement label. I've submitted a PR to fix that.

Also, I think you forgot to reopen this issue.

**Comment by rastislavcore** [comment]
merged & reopened this

**Comment by rastislavcore** [comment]
For this topic - we will try several wallets and use cases. But the first app, which is supporting the payto scheme is CorePass. We would like to be happy to see more integrations. Anyway, your point here is valid, but it needs to be tested if there is no need for shorthands, as CorePass has. This issue is blocked for now. Please, comment with use cases or another argument is needed.

**Comment by Pandapip1** [comment]
The specification for the `eth` payment type explicitly disallows 3-character currency codes: 

> If the currency is not a valid ERC-20 token, then the URI is invalid. This includes three-letter currency codes, which are not valid ERC-20 token addresses.

(From https://git.gnunet.org/gana.git/tree/payto-payment-target-types/eth.txt)

This is why I originally classified this as a bug. It doesn't follow the specification

**Comment by rastislavcore** [comment]
Following new structures in V2
