### ISSUE TITLE
Amount option is ignored when using Ethereum payment type

### ISSUE THREAD

**Issue by Pandapip1** [core-laboratories/payto#13]
### OS and version

Windows 11

### Bug

The Ethereum payment type ignores the user-provided amount when a custom currency is used. 

### Reproduce Bug

1. Select the Ethereum payment type 
2. Put in a contract address as a currency
3. Type in an amount

### Expected behavior

The URI should include both the currency and the amount in the amount parameter

**Comment by rastislavcore** [comment]
Tested and cannot reproduce.

One example is: `payto://eth/0x1f9090aaE28b8a3dCeaDf281B0F12828e676c326?amount=0xdAC17F958D2ee523a2206206994597C13D831ec7:100`

Tether Smart Contract running on Ethereum with an amount of 100 units.

Please, reopen if you are still facing that issue.

**Comment by Pandapip1** [comment]
Nor can I. Odd. I'll let you know if I can.
