### ISSUE TITLE
Populate chain IDs from chainlist.org

### ISSUE THREAD

**Issue by Pandapip1** [core-laboratories/payto#14]
### Problem

Currently, requesting payment on a specific chain requires knowing the chain ID.

### Solution

I propose that chainlist.org be used to search for chain IDs by name, and to populate the links (e.g. "Pay with Ethereum on Polygon Mainnet")

**Comment by rastislavcore** [comment]
Good improvement, but I propose PR creation. Not on the priority list so high right now.

**Comment by rastislavcore** [comment]
Closed because V2 is deployed, please consider open PR if you like to see it.
